storage:
  postgres:
    postgres_db:
      username:
        env: POSTGRES_USERNAME
      password: 
        env: POSTGRES_PASSWORD
      hostname:
        env: POSTGRES_HOST
      db_name:
        env: POSTGRES_DB
      port: 
        env: POSTGRES_PORT

run_queue:
  tag_concurrency_limits:
    - key: "process_image"
      value: "sam"
      limit: 1